# Generated by Django 6.0.2 on 2026-03-19 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_claimrequest_finder_lat_claimrequest_finder_lng_and_more'),
        ('qr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscan',
            name='scan_type',
            field=models.CharField(choices=[('user', 'User QR Scan'), ('item', 'Item QR Scan')], default='item', max_length=10),
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='items.item'),
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
