# Generated by Django 6.0.2 on 2026-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_is_superuser_user_is_admin_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
