# Generated by Django 6.0.3 on 2026-03-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='owner_response',
            field=models.TextField(blank=True, help_text='Owner can leave a note for the finder (e.g., request additional proof).'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='claims/proofs/'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='claims/proofs/'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='proof_requested',
            field=models.BooleanField(default=False),
        ),
    ]
