# Generated by Django 6.0.3 on 2026-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_claimrequest_owner_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='finder_lat',
            field=models.FloatField(blank=True, help_text='Last known latitude for the finder (shared after approval).', null=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='finder_lng',
            field=models.FloatField(blank=True, help_text='Last known longitude for the finder (shared after approval).', null=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='finder_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='pickup_confirmed',
            field=models.BooleanField(default=False, help_text='True when finder confirms they have picked up the item.'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='pickup_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
