# Generated by Django 6.0.3 on 2026-03-23 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_claimrequest_finder_lat_claimrequest_finder_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed'), ('returned', 'Returned'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='items.item')),
            ],
        ),
    ]
